# Generated by Django 5.0.6 on 2024-06-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_detail',
            fields=[
                ('Faculty_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Faculty_Name', models.CharField(max_length=50)),
                ('Faculty_Date_of_joining', models.DateTimeField()),
                ('Student_Branch', models.CharField(max_length=50)),
            ],
        ),
    ]
