# Generated by Django 5.0.6 on 2024-06-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_detail',
            old_name='Student_Branch',
            new_name='Faculty_Branch',
        ),
    ]
