# Generated by Django 5.0.6 on 2024-06-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branchModel',
            fields=[
                ('Branch_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Branch_Name', models.CharField(max_length=50)),
                ('Branch_HOD', models.CharField(max_length=50)),
            ],
        ),
    ]
