# Generated by Django 5.0.6 on 2024-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='Branch_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='Course_Details',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='Course_ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
