# Generated by Django 5.0.6 on 2024-06-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0002_remove_coursemodel_id_coursemodel_branch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_Model',
            fields=[
                ('Course_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Branch_ID', models.IntegerField(default=0)),
                ('Course_Details', models.CharField(default='NULL', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='courseModel',
        ),
    ]
