# Generated by Django 5.0.6 on 2024-06-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0003_course_model_delete_coursemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_model',
            old_name='Branch_ID',
            new_name='branch_ID',
        ),
        migrations.RenameField(
            model_name='course_model',
            old_name='Course_Details',
            new_name='course_Details',
        ),
        migrations.RenameField(
            model_name='course_model',
            old_name='Course_ID',
            new_name='course_ID',
        ),
    ]
