# Generated by Django 5.0.6 on 2024-06-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0005_rename_course_model_coursemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'managed': False},
        ),
    ]
