# Generated by Django 5.0.6 on 2024-06-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('Student_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=50)),
                ('Student_DOB', models.DateTimeField()),
                ('Student_Branch', models.CharField(max_length=50)),
                ('Student_Year', models.IntegerField()),
            ],
        ),
    ]
